DROP TABLE storageunititem CASCADE;
DROP TABLE item CASCADE;
DROP TABLE description CASCADE; 
DROP TABLE unitdoc CASCADE;
DROP TABLE storageunit CASCADE;
DROP TABLE newborntest CASCADE;
DROP TABLE test CASCADE;
DROP TABLE result CASCADE;
DROP TABLE newbornpathology CASCADE;
DROP TABLE newbornparent CASCADE;
DROP TABLE newborn CASCADE;
DROP TABLE person CASCADE;


